name: agri_tech_app
description: A premium AgriTech Flutter app for Indian farmers.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  provider: ^6.1.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  shared_preferences: ^2.5.4
  http: ^1.6.0
  fl_chart: ^0.66.2
  url_launcher: ^6.2.5
  intl: ^0.19.0
  dio: ^5.4.0
  html: ^0.15.4
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^17.2.2
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/data/crops.json
    - .env

